export const metricsSeed = [
  {
    key: 'freshness',
    label: 'Freshness',
    description: 'How recent is the signal?',
    enabled: true,
    order: 10,
    color: '#111827',
    strategy: 'freshness',
    config: {
      buckets: [
        { maxDays: 1, score: 100 },
        { maxDays: 7, score: 80 },
        { maxDays: 30, score: 50 },
        { maxDays: 99999, score: 20 },
      ],
      dateFields: ['publishedAt', 'createdAt'],
    },
  },
  {
    key: 'evidenceQuality',
    label: 'Evidence Quality',
    description: 'How strong/credible is the evidence?',
    enabled: true,
    order: 20,
    color: '#111827',
    strategy: 'evidenceQuality',
    config: {
      sourceBase: {
        simulated_patent: 80,
        patent: 80,
        regulatory: 85,
        simulated_news: 65,
        simulated_release: 65,
        simulated_forum: 40,
        forum: 40,
        reddit: 40,
      },
      urlBonusPer: 5,
      urlBonusCap: 20,
      defaultBase: 55,
    },
  },
  {
    key: 'relevance',
    label: 'Relevance',
    description: 'Fit to our use-case + competitors + keywords.',
    enabled: true,
    order: 30,
    color: '#111827',
    strategy: 'relevance',
    config: {
      competitorMentionScore: 30,
      keywordHitScore: 10,
      keywordHitCap: 40,
      useCaseMatchScore: 20,
      keywords: [
        'valve',
        'press fitting',
        'hydronic',
        'leak',
        'corrosion',
        'bim',
        'revit',
        'district heating',
        'heat pump',
        'retrofit',
      ],
    },
  },
] as const
